services:
  - type: web
    name: cca-backend
    runtime: docker
    plan: free
    region: singapore
    rootDir: backend
    envVars:
      - key: PORT
        value: 8000
    disk:
      name: cca-data
      mountPath: /app/data
      sizeGB: 1
